---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: cd-pipeline
spec:
  workspaces:
    - name: pipeline-workspace
  params:
    - name: repo-url
      type: string
    - name: branch
      type: string
      default: "main"
    - name: build-image
      type: string
  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: pipeline-workspace

    - name: git-clone
      taskRef:
        name: git-clone
        kind: ClusterTask
      runAfter:
        - cleanup
      workspaces:
        - name: output
          workspace: pipeline-workspace
      params:
        - name: url
          value: $(params.repo-url)
        - name: revision
          value: $(params.branch)

    - name: flake8
      taskRef:
        name: flake8
      runAfter:
        - git-clone
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: image
          value: "python:3.9-slim"
        - name: args
          value: "--count --max-complexity=10 --max-line-length=127 --statistics"

    - name: nose
      taskRef:
        name: nose
      runAfter:
        - flake8
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: args
          value: "-v --with-spec --spec-color"
        - name: database_uri
          value: "sqlite:///test.db"

    - name: buildah
      taskRef:
        name: buildah
        kind: ClusterTask
      runAfter:
        - nose
      workspaces:
        - name: source
          workspace: pipeline-workspace
      params:
        - name: IMAGE
          value: $(params.build-image)

    - name: deploy
      taskRef:
        name: openshift-client
        kind: ClusterTask
      runAfter:
        - buildah
      params:
        - name: SCRIPT
          value: |
            oc rollout restart deployment/cicd-project
            oc rollout status deployment/cicd-project
